name: ðŸš€ Deploy to EC2

# on:
#   push:
#     branches:
#       - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_DEPLOY_KEY }}
          script: |
            echo "â³ Starting deployment..."
            echo "ðŸ”‘ Setting up SSH..."
            eval "$(ssh-agent -s)"
            ssh-add ${{ secrets.EC2_GITHUB_KEY_PATH }}
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            echo "ðŸ”„ Pulling latest changes..."
            cd ${{ vars.EC2_APP_DIR }}
            git pull origin master
            echo "ðŸ“¦ Installing dependencies..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install
            echo "ðŸ”¨ Building app..."
            npm run build
            echo "ðŸš€ Restarting app"
            pm2 restart ${{ vars.EC2_PM2_NAME }}
            echo "âœ… Deployment complete!"
